### ISSUE TITLE
data convert error

### ISSUE THREAD

**Issue by pingfengluo** [TuXiaokang/pyseeta#1]
I am new to python.
when i ran your test.py . i got this error. any help will be pleasure, tks!

pyseeta/pyseeta/detector.py", line 77, in detect
    byte_data = (c_ubyte * image.size)(*image.tobytes())
TypeError: an integer is required

 numpy version is 1.12.1
 OS is : ubuntu 14.04

**Comment by TuXiaokang** [comment]
Thanks for your attention.
+ Are you sure is the image is valid？
+ Also I have updated the project, all images for testing have been provided. you can update & run it directly. 
plz contact me if you have any problems.
