### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by crazygirl1992** [TuXiaokang/pyseeta#10]
hello， i run your code,but the the accurate is bad, i use the model you provided,and need i train it?

**Comment by crazygirl1992** [comment]
hello， i run your code,but the the accurate is bad, i use the model you provided,and need i train it?
@TuXiaokang

**Comment by TuXiaokang** [comment]
Sorry for late reply. 
All model files are from by [official repo](https://github.com/seetaface/SeetaFaceEngine.git). it is hard to train ur own models because the training code is not provided.
