### ISSUE TITLE
ubuntu 安装报错version `GOMP_4.0' not found

### ISSUE THREAD

**Issue by xxllp** [TuXiaokang/pyseeta#8]
OSError: /home/melvin/anaconda2/bin/../lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/melvin/pyseeta/pyseeta/../SeetaFaceEngine/Release/libseeta_fd_lib.so)

**Comment by TuXiaokang** [comment]
This solution may be what you want : [stackoverflow](https://stackoverflow.com/questions/39912634/how-to-install-configure-caffe-python-anaconda-links-to-gomp-4-0-and-throws-er)

**Comment by xxllp** [comment]
还缺少文档哈

**Comment by TuXiaokang** [comment]
Yeah, but most of the usage can be found in `test.py`.

**Comment by xxllp** [comment]
python2.7 test.py
sim: [0.502326250076294, 0.26041379570961]
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /io/opencv/modules/highgui/src/window.cpp, line 583
Traceback (most recent call last):
  File "test.py", line 112, in <module>
    test_identifier()
  File "test.py", line 103, in test_identifier
    cv2.imshow('single', image_color_A)
cv2.error: /io/opencv/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

**Comment by xxllp** [comment]
还是不行哈，centos 上

**Comment by TuXiaokang** [comment]
The error occurs when calling `cv2.imshow` function.  
try `yum install gtk*` and rebuild `opencv`.

**Comment by xxllp** [comment]
opencv装不好

**Comment by xxllp** [comment]
我很好奇为啥人脸识别的定位里面会有个小圆形的，这个是系统的问题还是啥意思哈

**Comment by TuXiaokang** [comment]
All founded faces are sorted from large to small. the indicator in the lower-left corner is the index number of each face.

**Comment by xxllp** [comment]
这个数字能去掉吗~~

**Comment by TuXiaokang** [comment]
You can remove it by deleting the line 43 in `test.py`.

**Comment by xxllp** [comment]
还有个问题哈，模型文件导入是显示的，这个能默认吗，如果我安装在不同的机器上

**Comment by TuXiaokang** [comment]
It is recommended to use absolute path, currently. 
default path will be supported in the next release .

**Comment by xxllp** [comment]
好的，这里面最后一个能判断两个图片的相似度吗

**Comment by TuXiaokang** [comment]
it calculate the similarity of two faces, not images.

**Comment by xxllp** [comment]
这个计算相似度是根据什么算法来的，不是很明白

**Comment by TuXiaokang** [comment]
just the cosine distance.

**Comment by xxllp** [comment]
有些人脸太小识别不出来，修改最小大小好像还是不行

**Comment by TuXiaokang** [comment]
Missed detection is a problem for all algorithms.

**Comment by xxllp** [comment]
我判断很多face之间的相似度，有没有好的办法，而且我看test里面还 需要原图，这个能只根据faceid 来吗
