### ISSUE TITLE
Failed to map segment from shared object

### ISSUE THREAD

**Issue by andreyzhitnikov** [TuXiaokang/pyseeta#9]
Hi,
I'm trying to install the python package with
sudo python setup.py install 

I created directory Release  and run 
cd Release
cmake ..
make 

the files created in the folder  are 
![selection_009](https://user-images.githubusercontent.com/20877529/37861570-6a6f9d40-2f4d-11e8-8c4d-2a3ba1028bca.png)

when i run 
sudo python setup.py install
in appropriate directory  
I got the following error
![image](https://user-images.githubusercontent.com/20877529/37861583-a20a4520-2f4d-11e8-8aef-7a95fc1ffe70.png)

please help

**Comment by TuXiaokang** [comment]
maybe you can try clone and install it in other dirs (e.g. /home/xxx/Documents ), instead of removable storage.

**Comment by andreyzhitnikov** [comment]
it worked. 
thanks!
